# 产品或项目名称、软件开发公司名称
productName: JeeSite Demo
companyName: ThinkGem

# 产品版本、版权年份
productVersion: V4.2
copyrightYear: 2020

#是否演示模式
demoMode: false
server:

  port: 8999
  servlet:
    context-path: /car
  tomcat:
    uri-encoding: UTF-8
    
  # 将请求协议转换为 https
  schemeHttps: false
# 数据库连接
jdbc: 
  
  # Mysql 数据库配置
  type: mysql
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/car?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai
  username: root
  password: root
  testSql: SELECT 1

spring:
  
  # 应用程序名称
  application:
    name: jeesite-web
    
  # 环境名称（注意：不可设置为 test 它是单元测试专用的名称）
  profiles:
    active: default
    
  # 打印横幅
  main:
    bannerMode: "off"

# 日志配置
logging:
  config: classpath:config/logback-spring.xml
